import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

const brasika = localFont({
  src: '../public/fonts/brasika-display.otf',
  variable: '--font-brasika'
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${brasika.variable} font-serif`}>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
